{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "a49e291d",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 13,
   "id": "0cf10079",
   "metadata": {},
   "outputs": [],
   "source": [
    "data = pd.read_csv(\"D:\\STUDY\\Coding\\Jupyter Notebook\\DATA SCIENCE\\EDA\\LOAN DATA analysis\\DATA SET\\Loan 1.csv\")"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cc04cc62",
   "metadata": {},
   "source": [
    "#  Pandas DataFrame"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "b416007d",
   "metadata": {},
   "source": [
    "- A Pandas DataFrame is a two-dimensional data structure used in Python for data analysis. \n",
    "- It is similar to a table or a spreadsheet, where data is organized in rows and columns. \n",
    "- Each column has a name, and the data within the column can be of different types such as numeric, categorical, or text.\n",
    "- DataFrames are versatile and allow for a variety of data manipulation and analysis tasks, including filtering, sorting, grouping, merging, and visualizing.\n",
    "- We can create it using **DataFrame()** function"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "1eca1e57",
   "metadata": {},
   "source": [
    "## Creating a DataFrame"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "66595f91",
   "metadata": {},
   "source": [
    "Here, we create a Pandas DataFrame with the given sample data to demonstrate its structure and basic operations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 14,
   "id": "3ba6262d",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.DataFrame(data)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 15,
   "id": "d81ac87b",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "      Customer ID              Name Gender  Age  Income (USD)  \\\n",
      "0         C-26247  Tandra Olszewski      F   47       3472.69   \n",
      "1         C-35067     Jeannette Cha      F   57       1184.84   \n",
      "2         C-34590      Keva Godfrey      F   52       1266.27   \n",
      "3         C-16668      Elva Sackett      M   65       1369.72   \n",
      "4         C-12196    Sade Constable      F   60       1939.23   \n",
      "...           ...               ...    ...  ...           ...   \n",
      "19995      C-9076    Tobias Davilla      F   19       1349.60   \n",
      "19996     C-17587    Evelina Hodges      M   22       2019.78   \n",
      "19997     C-46479   Karlyn Mckinzie      M   19       2252.03   \n",
      "19998      C-3099    Mariana Pulver      F   21       1845.35   \n",
      "19999     C-43482   Mechelle Boddie      M   21       5233.16   \n",
      "\n",
      "      Income Stability            Profession Type of Employment    Location  \\\n",
      "0                  Low  Commercial associate           Managers  Semi-Urban   \n",
      "1                  Low               Working        Sales staff       Rural   \n",
      "2                  Low               Working                NaN  Semi-Urban   \n",
      "3                 High             Pensioner                NaN       Rural   \n",
      "4                 High             Pensioner                NaN       Urban   \n",
      "...                ...                   ...                ...         ...   \n",
      "19995              Low  Commercial associate                NaN  Semi-Urban   \n",
      "19996              Low               Working         Core staff       Urban   \n",
      "19997              Low               Working         Core staff  Semi-Urban   \n",
      "19998              Low               Working                NaN  Semi-Urban   \n",
      "19999              Low               Working           Laborers  Semi-Urban   \n",
      "\n",
      "       Loan Amount Request (USD)  ...  Dependents Credit Score  \\\n",
      "0                      137088.98  ...         2.0       799.14   \n",
      "1                      104771.59  ...         2.0       833.31   \n",
      "2                      176684.91  ...         3.0       627.44   \n",
      "3                       97009.18  ...         2.0       833.20   \n",
      "4                      109980.00  ...         NaN          NaN   \n",
      "...                          ...  ...         ...          ...   \n",
      "19995                  156766.97  ...         4.0       684.32   \n",
      "19996                   47924.80  ...         NaN       706.34   \n",
      "19997                   18629.88  ...         1.0       656.46   \n",
      "19998                   95430.73  ...         2.0       865.46   \n",
      "19999                  107966.03  ...         3.0       857.16   \n",
      "\n",
      "      No. of Defaults  Has Active Credit Card  Property ID  Property Age  \\\n",
      "0                   0             Unpossessed          843       3472.69   \n",
      "1                   0             Unpossessed           22       1184.84   \n",
      "2                   0             Unpossessed            1       1266.27   \n",
      "3                   0                Inactive          730       1369.72   \n",
      "4                   0                     NaN          356       1939.23   \n",
      "...               ...                     ...          ...           ...   \n",
      "19995               0                Inactive          681       1349.60   \n",
      "19996               0                Inactive          213       2019.78   \n",
      "19997               0                Inactive          270       2252.03   \n",
      "19998               0             Unpossessed          489       1845.35   \n",
      "19999               1                  Active          368       5233.16   \n",
      "\n",
      "      Property Type  Property Location  Co-Applicant  Property Price  \n",
      "0                 2              Urban             1        236644.5  \n",
      "1                 1              Rural             1        142357.3  \n",
      "2                 1              Urban             1       300991.24  \n",
      "3                 1         Semi-Urban             0        125612.1  \n",
      "4                 4         Semi-Urban             1          180908  \n",
      "...             ...                ...           ...             ...  \n",
      "19995             4         Semi-Urban             1          212778  \n",
      "19996             4              Urban             1        90816.95  \n",
      "19997             2              Rural             0        21566.27  \n",
      "19998             1         Semi-Urban             1       120281.17  \n",
      "19999             4         Semi-Urban             0       133425.43  \n",
      "\n",
      "[20000 rows x 23 columns]\n"
     ]
    }
   ],
   "source": [
    "# Display the DataFrame\n",
    "print(df)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "a1bb5418",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Customer ID</th>\n",
       "      <th>Name</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Income (USD)</th>\n",
       "      <th>Income Stability</th>\n",
       "      <th>Profession</th>\n",
       "      <th>Type of Employment</th>\n",
       "      <th>Location</th>\n",
       "      <th>Loan Amount Request (USD)</th>\n",
       "      <th>...</th>\n",
       "      <th>Dependents</th>\n",
       "      <th>Credit Score</th>\n",
       "      <th>No. of Defaults</th>\n",
       "      <th>Has Active Credit Card</th>\n",
       "      <th>Property ID</th>\n",
       "      <th>Property Age</th>\n",
       "      <th>Property Type</th>\n",
       "      <th>Property Location</th>\n",
       "      <th>Co-Applicant</th>\n",
       "      <th>Property Price</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>C-26247</td>\n",
       "      <td>Tandra Olszewski</td>\n",
       "      <td>F</td>\n",
       "      <td>47</td>\n",
       "      <td>3472.69</td>\n",
       "      <td>Low</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Managers</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>137088.98</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>799.14</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>843</td>\n",
       "      <td>3472.69</td>\n",
       "      <td>2</td>\n",
       "      <td>Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>236644.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>C-35067</td>\n",
       "      <td>Jeannette Cha</td>\n",
       "      <td>F</td>\n",
       "      <td>57</td>\n",
       "      <td>1184.84</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Sales staff</td>\n",
       "      <td>Rural</td>\n",
       "      <td>104771.59</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>833.31</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>22</td>\n",
       "      <td>1184.84</td>\n",
       "      <td>1</td>\n",
       "      <td>Rural</td>\n",
       "      <td>1</td>\n",
       "      <td>142357.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>C-34590</td>\n",
       "      <td>Keva Godfrey</td>\n",
       "      <td>F</td>\n",
       "      <td>52</td>\n",
       "      <td>1266.27</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>176684.91</td>\n",
       "      <td>...</td>\n",
       "      <td>3.0</td>\n",
       "      <td>627.44</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>1</td>\n",
       "      <td>1266.27</td>\n",
       "      <td>1</td>\n",
       "      <td>Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>300991.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>C-16668</td>\n",
       "      <td>Elva Sackett</td>\n",
       "      <td>M</td>\n",
       "      <td>65</td>\n",
       "      <td>1369.72</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Rural</td>\n",
       "      <td>97009.18</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>833.20</td>\n",
       "      <td>0</td>\n",
       "      <td>Inactive</td>\n",
       "      <td>730</td>\n",
       "      <td>1369.72</td>\n",
       "      <td>1</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>0</td>\n",
       "      <td>125612.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>C-12196</td>\n",
       "      <td>Sade Constable</td>\n",
       "      <td>F</td>\n",
       "      <td>60</td>\n",
       "      <td>1939.23</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Urban</td>\n",
       "      <td>109980.00</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>356</td>\n",
       "      <td>1939.23</td>\n",
       "      <td>4</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>180908</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19995</th>\n",
       "      <td>C-9076</td>\n",
       "      <td>Tobias Davilla</td>\n",
       "      <td>F</td>\n",
       "      <td>19</td>\n",
       "      <td>1349.60</td>\n",
       "      <td>Low</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>156766.97</td>\n",
       "      <td>...</td>\n",
       "      <td>4.0</td>\n",
       "      <td>684.32</td>\n",
       "      <td>0</td>\n",
       "      <td>Inactive</td>\n",
       "      <td>681</td>\n",
       "      <td>1349.60</td>\n",
       "      <td>4</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>212778</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19996</th>\n",
       "      <td>C-17587</td>\n",
       "      <td>Evelina Hodges</td>\n",
       "      <td>M</td>\n",
       "      <td>22</td>\n",
       "      <td>2019.78</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Core staff</td>\n",
       "      <td>Urban</td>\n",
       "      <td>47924.80</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>706.34</td>\n",
       "      <td>0</td>\n",
       "      <td>Inactive</td>\n",
       "      <td>213</td>\n",
       "      <td>2019.78</td>\n",
       "      <td>4</td>\n",
       "      <td>Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>90816.95</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19997</th>\n",
       "      <td>C-46479</td>\n",
       "      <td>Karlyn Mckinzie</td>\n",
       "      <td>M</td>\n",
       "      <td>19</td>\n",
       "      <td>2252.03</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Core staff</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>18629.88</td>\n",
       "      <td>...</td>\n",
       "      <td>1.0</td>\n",
       "      <td>656.46</td>\n",
       "      <td>0</td>\n",
       "      <td>Inactive</td>\n",
       "      <td>270</td>\n",
       "      <td>2252.03</td>\n",
       "      <td>2</td>\n",
       "      <td>Rural</td>\n",
       "      <td>0</td>\n",
       "      <td>21566.27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19998</th>\n",
       "      <td>C-3099</td>\n",
       "      <td>Mariana Pulver</td>\n",
       "      <td>F</td>\n",
       "      <td>21</td>\n",
       "      <td>1845.35</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>95430.73</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>865.46</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>489</td>\n",
       "      <td>1845.35</td>\n",
       "      <td>1</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>120281.17</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19999</th>\n",
       "      <td>C-43482</td>\n",
       "      <td>Mechelle Boddie</td>\n",
       "      <td>M</td>\n",
       "      <td>21</td>\n",
       "      <td>5233.16</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Laborers</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>107966.03</td>\n",
       "      <td>...</td>\n",
       "      <td>3.0</td>\n",
       "      <td>857.16</td>\n",
       "      <td>1</td>\n",
       "      <td>Active</td>\n",
       "      <td>368</td>\n",
       "      <td>5233.16</td>\n",
       "      <td>4</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>0</td>\n",
       "      <td>133425.43</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>20000 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "      Customer ID              Name Gender  Age  Income (USD)  \\\n",
       "0         C-26247  Tandra Olszewski      F   47       3472.69   \n",
       "1         C-35067     Jeannette Cha      F   57       1184.84   \n",
       "2         C-34590      Keva Godfrey      F   52       1266.27   \n",
       "3         C-16668      Elva Sackett      M   65       1369.72   \n",
       "4         C-12196    Sade Constable      F   60       1939.23   \n",
       "...           ...               ...    ...  ...           ...   \n",
       "19995      C-9076    Tobias Davilla      F   19       1349.60   \n",
       "19996     C-17587    Evelina Hodges      M   22       2019.78   \n",
       "19997     C-46479   Karlyn Mckinzie      M   19       2252.03   \n",
       "19998      C-3099    Mariana Pulver      F   21       1845.35   \n",
       "19999     C-43482   Mechelle Boddie      M   21       5233.16   \n",
       "\n",
       "      Income Stability            Profession Type of Employment    Location  \\\n",
       "0                  Low  Commercial associate           Managers  Semi-Urban   \n",
       "1                  Low               Working        Sales staff       Rural   \n",
       "2                  Low               Working                NaN  Semi-Urban   \n",
       "3                 High             Pensioner                NaN       Rural   \n",
       "4                 High             Pensioner                NaN       Urban   \n",
       "...                ...                   ...                ...         ...   \n",
       "19995              Low  Commercial associate                NaN  Semi-Urban   \n",
       "19996              Low               Working         Core staff       Urban   \n",
       "19997              Low               Working         Core staff  Semi-Urban   \n",
       "19998              Low               Working                NaN  Semi-Urban   \n",
       "19999              Low               Working           Laborers  Semi-Urban   \n",
       "\n",
       "       Loan Amount Request (USD)  ...  Dependents Credit Score  \\\n",
       "0                      137088.98  ...         2.0       799.14   \n",
       "1                      104771.59  ...         2.0       833.31   \n",
       "2                      176684.91  ...         3.0       627.44   \n",
       "3                       97009.18  ...         2.0       833.20   \n",
       "4                      109980.00  ...         NaN          NaN   \n",
       "...                          ...  ...         ...          ...   \n",
       "19995                  156766.97  ...         4.0       684.32   \n",
       "19996                   47924.80  ...         NaN       706.34   \n",
       "19997                   18629.88  ...         1.0       656.46   \n",
       "19998                   95430.73  ...         2.0       865.46   \n",
       "19999                  107966.03  ...         3.0       857.16   \n",
       "\n",
       "      No. of Defaults  Has Active Credit Card  Property ID  Property Age  \\\n",
       "0                   0             Unpossessed          843       3472.69   \n",
       "1                   0             Unpossessed           22       1184.84   \n",
       "2                   0             Unpossessed            1       1266.27   \n",
       "3                   0                Inactive          730       1369.72   \n",
       "4                   0                     NaN          356       1939.23   \n",
       "...               ...                     ...          ...           ...   \n",
       "19995               0                Inactive          681       1349.60   \n",
       "19996               0                Inactive          213       2019.78   \n",
       "19997               0                Inactive          270       2252.03   \n",
       "19998               0             Unpossessed          489       1845.35   \n",
       "19999               1                  Active          368       5233.16   \n",
       "\n",
       "      Property Type  Property Location  Co-Applicant  Property Price  \n",
       "0                 2              Urban             1        236644.5  \n",
       "1                 1              Rural             1        142357.3  \n",
       "2                 1              Urban             1       300991.24  \n",
       "3                 1         Semi-Urban             0        125612.1  \n",
       "4                 4         Semi-Urban             1          180908  \n",
       "...             ...                ...           ...             ...  \n",
       "19995             4         Semi-Urban             1          212778  \n",
       "19996             4              Urban             1        90816.95  \n",
       "19997             2              Rural             0        21566.27  \n",
       "19998             1         Semi-Urban             1       120281.17  \n",
       "19999             4         Semi-Urban             0       133425.43  \n",
       "\n",
       "[20000 rows x 23 columns]"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# or simply\n",
    "df"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c8fab074",
   "metadata": {},
   "source": [
    "This code snippet creates a DataFrame with the provided data and displays it, giving you a sense of the structure and organization of the dataset."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4c1327f0",
   "metadata": {},
   "source": [
    "### Creating a DataFrame from Dictionaries"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "36154570",
   "metadata": {},
   "source": [
    "- Pandas DataFrames are a convenient way to work with tabular data in Python. \n",
    "- You can create a DataFrame from various sources, such as dictionaries, lists, or CSV files. Let's start by creating a \n",
    "- DataFrame from a dictionary to demonstrate basic structure and operations."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 17,
   "id": "c603f34a",
   "metadata": {},
   "outputs": [],
   "source": [
    "# Create a dictionary with the provided data\n",
    "data1 = {\n",
    "    \"Customer ID\": [\"C-26247\", \"C-35067\", \"C-34590\", \"C-16668\", \"C-12196\", \"C-2600\", \"C-9047\", \"C-2206\", \"C-25607\", \"C-11606\"],\n",
    "    \"Name\": [\"Tandra Olszewski\", \"Jeannette Cha\", \"Keva Godfrey\", \"Elva Sackett\", \"Sade Constable\", \"Gina Weir\", \"Lacey Cybulski\", \"Karrie Dickison\", \n",
    "             \"Tona Wigington\", \"Hellen Alexis\"],\n",
    "    \"Gender\": [\"F\", \"F\", \"F\", \"M\", \"F\", \"F\", \"M\", \"M\", \"M\", \"F\"],\n",
    "    \"Age\": [47, 57, 52, 65, 60, 59, 43, 65, 64, 27],\n",
    "    \"Income (USD)\": [3472.69, 1184.84, 1266.27, 1369.72, 1939.23, 2944.81, 1957.31, 1403.63, 1604.65, 949.17],\n",
    "    \"Income Stability\": [\"Low\", \"Low\", \"Low\", \"High\", \"High\", \"Low\", \"Low\", \"High\", \"Low\", \"Working\"],\n",
    "    \"Profession\": [\"Commercial associate\", \"Working\", \"Working\", \"Pensioner\", \"Pensioner\", \"Working\", \"Working\", \"Pensioner\", \"Working\", \"Working\"],\n",
    "    \"Type of Employment\": [\"Managers\", \"Sales staff\", \"\", \"\", \"\", \"Sales staff\", \"Sales staff\", \"\", \"\", \"Laborers\"],\n",
    "    \"Location\": [\"Semi-Urban\", \"Rural\", \"Semi-Urban\", \"Rural\", \"Urban\", \"Semi-Urban\", \"Rural\", \"Semi-Urban\", \"Semi-Urban\", \"Rural\"],\n",
    "    \"Loan Amount Request (USD)\": [137088.98, 104771.59, 176684.91, 97009.18, 109980, 31465.78, 150334.11, 121029.27, 39475.31, 24703.89]\n",
    "}"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 18,
   "id": "1546dc95",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Customer ID</th>\n",
       "      <th>Name</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Income (USD)</th>\n",
       "      <th>Income Stability</th>\n",
       "      <th>Profession</th>\n",
       "      <th>Type of Employment</th>\n",
       "      <th>Location</th>\n",
       "      <th>Loan Amount Request (USD)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>C-26247</td>\n",
       "      <td>Tandra Olszewski</td>\n",
       "      <td>F</td>\n",
       "      <td>47</td>\n",
       "      <td>3472.69</td>\n",
       "      <td>Low</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Managers</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>137088.98</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>C-35067</td>\n",
       "      <td>Jeannette Cha</td>\n",
       "      <td>F</td>\n",
       "      <td>57</td>\n",
       "      <td>1184.84</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Sales staff</td>\n",
       "      <td>Rural</td>\n",
       "      <td>104771.59</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>C-34590</td>\n",
       "      <td>Keva Godfrey</td>\n",
       "      <td>F</td>\n",
       "      <td>52</td>\n",
       "      <td>1266.27</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td></td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>176684.91</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>C-16668</td>\n",
       "      <td>Elva Sackett</td>\n",
       "      <td>M</td>\n",
       "      <td>65</td>\n",
       "      <td>1369.72</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td></td>\n",
       "      <td>Rural</td>\n",
       "      <td>97009.18</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>C-12196</td>\n",
       "      <td>Sade Constable</td>\n",
       "      <td>F</td>\n",
       "      <td>60</td>\n",
       "      <td>1939.23</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td></td>\n",
       "      <td>Urban</td>\n",
       "      <td>109980.00</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>C-2600</td>\n",
       "      <td>Gina Weir</td>\n",
       "      <td>F</td>\n",
       "      <td>59</td>\n",
       "      <td>2944.81</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Sales staff</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>31465.78</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>C-9047</td>\n",
       "      <td>Lacey Cybulski</td>\n",
       "      <td>M</td>\n",
       "      <td>43</td>\n",
       "      <td>1957.31</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Sales staff</td>\n",
       "      <td>Rural</td>\n",
       "      <td>150334.11</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>C-2206</td>\n",
       "      <td>Karrie Dickison</td>\n",
       "      <td>M</td>\n",
       "      <td>65</td>\n",
       "      <td>1403.63</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td></td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>121029.27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>C-25607</td>\n",
       "      <td>Tona Wigington</td>\n",
       "      <td>M</td>\n",
       "      <td>64</td>\n",
       "      <td>1604.65</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td></td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>39475.31</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>C-11606</td>\n",
       "      <td>Hellen Alexis</td>\n",
       "      <td>F</td>\n",
       "      <td>27</td>\n",
       "      <td>949.17</td>\n",
       "      <td>Working</td>\n",
       "      <td>Working</td>\n",
       "      <td>Laborers</td>\n",
       "      <td>Rural</td>\n",
       "      <td>24703.89</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Customer ID              Name Gender  Age  Income (USD) Income Stability  \\\n",
       "0     C-26247  Tandra Olszewski      F   47       3472.69              Low   \n",
       "1     C-35067     Jeannette Cha      F   57       1184.84              Low   \n",
       "2     C-34590      Keva Godfrey      F   52       1266.27              Low   \n",
       "3     C-16668      Elva Sackett      M   65       1369.72             High   \n",
       "4     C-12196    Sade Constable      F   60       1939.23             High   \n",
       "5      C-2600         Gina Weir      F   59       2944.81              Low   \n",
       "6      C-9047    Lacey Cybulski      M   43       1957.31              Low   \n",
       "7      C-2206   Karrie Dickison      M   65       1403.63             High   \n",
       "8     C-25607    Tona Wigington      M   64       1604.65              Low   \n",
       "9     C-11606     Hellen Alexis      F   27        949.17          Working   \n",
       "\n",
       "             Profession Type of Employment    Location  \\\n",
       "0  Commercial associate           Managers  Semi-Urban   \n",
       "1               Working        Sales staff       Rural   \n",
       "2               Working                     Semi-Urban   \n",
       "3             Pensioner                          Rural   \n",
       "4             Pensioner                          Urban   \n",
       "5               Working        Sales staff  Semi-Urban   \n",
       "6               Working        Sales staff       Rural   \n",
       "7             Pensioner                     Semi-Urban   \n",
       "8               Working                     Semi-Urban   \n",
       "9               Working           Laborers       Rural   \n",
       "\n",
       "   Loan Amount Request (USD)  \n",
       "0                  137088.98  \n",
       "1                  104771.59  \n",
       "2                  176684.91  \n",
       "3                   97009.18  \n",
       "4                  109980.00  \n",
       "5                   31465.78  \n",
       "6                  150334.11  \n",
       "7                  121029.27  \n",
       "8                   39475.31  \n",
       "9                   24703.89  "
      ]
     },
     "execution_count": 18,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Creating DATAFRAME and printing it \n",
    "data2 = pd.DataFrame(data1)\n",
    "data2"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4682b37f",
   "metadata": {},
   "source": [
    "So, using Dataframe function we can create database from the dictionaries of values that we had."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "2f0d791c",
   "metadata": {},
   "source": [
    "### Creating a DataFrame from a CSV File"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "a0f2a55d",
   "metadata": {},
   "source": [
    "You can also create a DataFrame by reading data from a CSV file. This is useful when working with large datasets or when you need to select specific columns."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 19,
   "id": "ec6dc149",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Customer ID</th>\n",
       "      <th>Name</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Income (USD)</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>C-26247</td>\n",
       "      <td>Tandra Olszewski</td>\n",
       "      <td>F</td>\n",
       "      <td>3472.69</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>C-35067</td>\n",
       "      <td>Jeannette Cha</td>\n",
       "      <td>F</td>\n",
       "      <td>1184.84</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>C-34590</td>\n",
       "      <td>Keva Godfrey</td>\n",
       "      <td>F</td>\n",
       "      <td>1266.27</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>C-16668</td>\n",
       "      <td>Elva Sackett</td>\n",
       "      <td>M</td>\n",
       "      <td>1369.72</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>C-12196</td>\n",
       "      <td>Sade Constable</td>\n",
       "      <td>F</td>\n",
       "      <td>1939.23</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "  Customer ID              Name Gender  Income (USD)\n",
       "0     C-26247  Tandra Olszewski      F       3472.69\n",
       "1     C-35067     Jeannette Cha      F       1184.84\n",
       "2     C-34590      Keva Godfrey      F       1266.27\n",
       "3     C-16668      Elva Sackett      M       1369.72\n",
       "4     C-12196    Sade Constable      F       1939.23"
      ]
     },
     "execution_count": 19,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Define the columns to select from the CSV file\n",
    "selected_columns = [\"Customer ID\", \"Name\", \"Gender\", \"Income (USD)\"]\n",
    "\n",
    "# Read the CSV file and select specific columns\n",
    "df_from_csv = pd.read_csv(\"D:\\STUDY\\Coding\\Jupyter Notebook\\DATA SCIENCE\\EDA\\LOAN DATA analysis\\DATA SET\\Loan 1.csv\", usecols=selected_columns)\n",
    "\n",
    "# Display the first few rows to confirm the selection\n",
    "df_from_csv.head()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "84aec8a7",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "4442a631",
   "metadata": {},
   "source": [
    "# Data Inspection"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "6bbe82d4",
   "metadata": {},
   "source": [
    "- Data inspection is the process of examining a DataFrame to understand its structure, check for missing or inconsistent data, and learn about the data types of each column. \n",
    "- It provides insights into potential data issues and guides further data cleaning and analysis."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e25a8dd3",
   "metadata": {},
   "source": [
    "## Data Inspection Functions and their Meaning"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "c5a574b9",
   "metadata": {},
   "source": [
    "1. **df.info()**: Provides information about the DataFrame, including the number of rows, columns, data types, and any missing data.\n",
    "2. **df.head(n)**: Displays the first n rows of the DataFrame, useful for a quick overview.\n",
    "3. **df.describe()**: Generates summary statistics for numerical columns, including count, mean, standard deviation, minimum, maximum, and quartiles.\n",
    "4. **df.isnull().sum()**: Returns the count of missing values in each column, helping identify data quality issues.\n",
    "5. **df.columns**: Lists the column names in the DataFrame.\n",
    "6. **df.dtypes**: Shows the data types for each column, useful for detecting inconsistencies."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 20,
   "id": "b710b6fd",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "<class 'pandas.core.frame.DataFrame'>\n",
      "RangeIndex: 20000 entries, 0 to 19999\n",
      "Data columns (total 23 columns):\n",
      " #   Column                       Non-Null Count  Dtype  \n",
      "---  ------                       --------------  -----  \n",
      " 0   Customer ID                  20000 non-null  object \n",
      " 1   Name                         20000 non-null  object \n",
      " 2   Gender                       19969 non-null  object \n",
      " 3   Age                          20000 non-null  int64  \n",
      " 4   Income (USD)                 19250 non-null  float64\n",
      " 5   Income Stability             19187 non-null  object \n",
      " 6   Profession                   20000 non-null  object \n",
      " 7   Type of Employment           15311 non-null  object \n",
      " 8   Location                     20000 non-null  object \n",
      " 9   Loan Amount Request (USD)    20000 non-null  float64\n",
      " 10  Current Loan Expenses (USD)  19917 non-null  float64\n",
      " 11  Expense Type 1               20000 non-null  object \n",
      " 12  Expense Type 2               20000 non-null  object \n",
      " 13  Dependents                   18858 non-null  float64\n",
      " 14  Credit Score                 19257 non-null  float64\n",
      " 15  No. of Defaults              20000 non-null  int64  \n",
      " 16  Has Active Credit Card       18924 non-null  object \n",
      " 17  Property ID                  20000 non-null  int64  \n",
      " 18  Property Age                 19108 non-null  float64\n",
      " 19  Property Type                20000 non-null  int64  \n",
      " 20  Property Location            19840 non-null  object \n",
      " 21  Co-Applicant                 20000 non-null  object \n",
      " 22  Property Price               20000 non-null  object \n",
      "dtypes: float64(6), int64(4), object(13)\n",
      "memory usage: 3.5+ MB\n"
     ]
    }
   ],
   "source": [
    "# Check the structure and basic information of the DataFrame\n",
    "df.info()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 21,
   "id": "4800aabe",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Customer ID</th>\n",
       "      <th>Name</th>\n",
       "      <th>Gender</th>\n",
       "      <th>Age</th>\n",
       "      <th>Income (USD)</th>\n",
       "      <th>Income Stability</th>\n",
       "      <th>Profession</th>\n",
       "      <th>Type of Employment</th>\n",
       "      <th>Location</th>\n",
       "      <th>Loan Amount Request (USD)</th>\n",
       "      <th>...</th>\n",
       "      <th>Dependents</th>\n",
       "      <th>Credit Score</th>\n",
       "      <th>No. of Defaults</th>\n",
       "      <th>Has Active Credit Card</th>\n",
       "      <th>Property ID</th>\n",
       "      <th>Property Age</th>\n",
       "      <th>Property Type</th>\n",
       "      <th>Property Location</th>\n",
       "      <th>Co-Applicant</th>\n",
       "      <th>Property Price</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>C-26247</td>\n",
       "      <td>Tandra Olszewski</td>\n",
       "      <td>F</td>\n",
       "      <td>47</td>\n",
       "      <td>3472.69</td>\n",
       "      <td>Low</td>\n",
       "      <td>Commercial associate</td>\n",
       "      <td>Managers</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>137088.98</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>799.14</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>843</td>\n",
       "      <td>3472.69</td>\n",
       "      <td>2</td>\n",
       "      <td>Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>236644.5</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>C-35067</td>\n",
       "      <td>Jeannette Cha</td>\n",
       "      <td>F</td>\n",
       "      <td>57</td>\n",
       "      <td>1184.84</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>Sales staff</td>\n",
       "      <td>Rural</td>\n",
       "      <td>104771.59</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>833.31</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>22</td>\n",
       "      <td>1184.84</td>\n",
       "      <td>1</td>\n",
       "      <td>Rural</td>\n",
       "      <td>1</td>\n",
       "      <td>142357.3</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>C-34590</td>\n",
       "      <td>Keva Godfrey</td>\n",
       "      <td>F</td>\n",
       "      <td>52</td>\n",
       "      <td>1266.27</td>\n",
       "      <td>Low</td>\n",
       "      <td>Working</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>176684.91</td>\n",
       "      <td>...</td>\n",
       "      <td>3.0</td>\n",
       "      <td>627.44</td>\n",
       "      <td>0</td>\n",
       "      <td>Unpossessed</td>\n",
       "      <td>1</td>\n",
       "      <td>1266.27</td>\n",
       "      <td>1</td>\n",
       "      <td>Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>300991.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>C-16668</td>\n",
       "      <td>Elva Sackett</td>\n",
       "      <td>M</td>\n",
       "      <td>65</td>\n",
       "      <td>1369.72</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Rural</td>\n",
       "      <td>97009.18</td>\n",
       "      <td>...</td>\n",
       "      <td>2.0</td>\n",
       "      <td>833.20</td>\n",
       "      <td>0</td>\n",
       "      <td>Inactive</td>\n",
       "      <td>730</td>\n",
       "      <td>1369.72</td>\n",
       "      <td>1</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>0</td>\n",
       "      <td>125612.1</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>C-12196</td>\n",
       "      <td>Sade Constable</td>\n",
       "      <td>F</td>\n",
       "      <td>60</td>\n",
       "      <td>1939.23</td>\n",
       "      <td>High</td>\n",
       "      <td>Pensioner</td>\n",
       "      <td>NaN</td>\n",
       "      <td>Urban</td>\n",
       "      <td>109980.00</td>\n",
       "      <td>...</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>0</td>\n",
       "      <td>NaN</td>\n",
       "      <td>356</td>\n",
       "      <td>1939.23</td>\n",
       "      <td>4</td>\n",
       "      <td>Semi-Urban</td>\n",
       "      <td>1</td>\n",
       "      <td>180908</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>5 rows × 23 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "  Customer ID              Name Gender  Age  Income (USD) Income Stability  \\\n",
       "0     C-26247  Tandra Olszewski      F   47       3472.69              Low   \n",
       "1     C-35067     Jeannette Cha      F   57       1184.84              Low   \n",
       "2     C-34590      Keva Godfrey      F   52       1266.27              Low   \n",
       "3     C-16668      Elva Sackett      M   65       1369.72             High   \n",
       "4     C-12196    Sade Constable      F   60       1939.23             High   \n",
       "\n",
       "             Profession Type of Employment    Location  \\\n",
       "0  Commercial associate           Managers  Semi-Urban   \n",
       "1               Working        Sales staff       Rural   \n",
       "2               Working                NaN  Semi-Urban   \n",
       "3             Pensioner                NaN       Rural   \n",
       "4             Pensioner                NaN       Urban   \n",
       "\n",
       "   Loan Amount Request (USD)  ...  Dependents Credit Score No. of Defaults  \\\n",
       "0                  137088.98  ...         2.0       799.14               0   \n",
       "1                  104771.59  ...         2.0       833.31               0   \n",
       "2                  176684.91  ...         3.0       627.44               0   \n",
       "3                   97009.18  ...         2.0       833.20               0   \n",
       "4                  109980.00  ...         NaN          NaN               0   \n",
       "\n",
       "   Has Active Credit Card  Property ID  Property Age Property Type  \\\n",
       "0             Unpossessed          843       3472.69             2   \n",
       "1             Unpossessed           22       1184.84             1   \n",
       "2             Unpossessed            1       1266.27             1   \n",
       "3                Inactive          730       1369.72             1   \n",
       "4                     NaN          356       1939.23             4   \n",
       "\n",
       "   Property Location  Co-Applicant  Property Price  \n",
       "0              Urban             1        236644.5  \n",
       "1              Rural             1        142357.3  \n",
       "2              Urban             1       300991.24  \n",
       "3         Semi-Urban             0        125612.1  \n",
       "4         Semi-Urban             1          180908  \n",
       "\n",
       "[5 rows x 23 columns]"
      ]
     },
     "execution_count": 21,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Display the first 5 rows to inspect the data\n",
    "df.head(5)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 22,
   "id": "46852883",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Age</th>\n",
       "      <th>Income (USD)</th>\n",
       "      <th>Loan Amount Request (USD)</th>\n",
       "      <th>Current Loan Expenses (USD)</th>\n",
       "      <th>Dependents</th>\n",
       "      <th>Credit Score</th>\n",
       "      <th>No. of Defaults</th>\n",
       "      <th>Property ID</th>\n",
       "      <th>Property Age</th>\n",
       "      <th>Property Type</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>count</th>\n",
       "      <td>20000.000000</td>\n",
       "      <td>19250.000000</td>\n",
       "      <td>20000.000000</td>\n",
       "      <td>19917.000000</td>\n",
       "      <td>18858.000000</td>\n",
       "      <td>19257.000000</td>\n",
       "      <td>20000.000000</td>\n",
       "      <td>20000.000000</td>\n",
       "      <td>19108.000000</td>\n",
       "      <td>20000.00000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>mean</th>\n",
       "      <td>39.940500</td>\n",
       "      <td>2536.995394</td>\n",
       "      <td>88859.076706</td>\n",
       "      <td>408.462359</td>\n",
       "      <td>2.251246</td>\n",
       "      <td>738.821538</td>\n",
       "      <td>0.189500</td>\n",
       "      <td>501.024500</td>\n",
       "      <td>2534.102003</td>\n",
       "      <td>2.47190</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>std</th>\n",
       "      <td>16.097618</td>\n",
       "      <td>1415.908803</td>\n",
       "      <td>60007.333673</td>\n",
       "      <td>215.846532</td>\n",
       "      <td>0.953153</td>\n",
       "      <td>72.406504</td>\n",
       "      <td>0.391915</td>\n",
       "      <td>287.537722</td>\n",
       "      <td>1408.509255</td>\n",
       "      <td>1.12551</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>min</th>\n",
       "      <td>18.000000</td>\n",
       "      <td>368.590000</td>\n",
       "      <td>6185.480000</td>\n",
       "      <td>41.370000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>580.040000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>368.590000</td>\n",
       "      <td>1.00000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>25%</th>\n",
       "      <td>25.000000</td>\n",
       "      <td>1659.722500</td>\n",
       "      <td>40889.030000</td>\n",
       "      <td>250.890000</td>\n",
       "      <td>2.000000</td>\n",
       "      <td>680.300000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>252.000000</td>\n",
       "      <td>1658.397500</td>\n",
       "      <td>1.00000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>50%</th>\n",
       "      <td>40.000000</td>\n",
       "      <td>2224.590000</td>\n",
       "      <td>74565.990000</td>\n",
       "      <td>374.000000</td>\n",
       "      <td>2.000000</td>\n",
       "      <td>739.300000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>501.000000</td>\n",
       "      <td>2220.605000</td>\n",
       "      <td>2.00000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>75%</th>\n",
       "      <td>55.000000</td>\n",
       "      <td>3082.925000</td>\n",
       "      <td>120068.852500</td>\n",
       "      <td>519.570000</td>\n",
       "      <td>3.000000</td>\n",
       "      <td>797.440000</td>\n",
       "      <td>0.000000</td>\n",
       "      <td>748.000000</td>\n",
       "      <td>3082.250000</td>\n",
       "      <td>3.00000</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>max</th>\n",
       "      <td>65.000000</td>\n",
       "      <td>30427.680000</td>\n",
       "      <td>576335.680000</td>\n",
       "      <td>3305.970000</td>\n",
       "      <td>13.000000</td>\n",
       "      <td>893.830000</td>\n",
       "      <td>1.000000</td>\n",
       "      <td>999.000000</td>\n",
       "      <td>30427.680000</td>\n",
       "      <td>4.00000</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "                Age  Income (USD)  Loan Amount Request (USD)  \\\n",
       "count  20000.000000  19250.000000               20000.000000   \n",
       "mean      39.940500   2536.995394               88859.076706   \n",
       "std       16.097618   1415.908803               60007.333673   \n",
       "min       18.000000    368.590000                6185.480000   \n",
       "25%       25.000000   1659.722500               40889.030000   \n",
       "50%       40.000000   2224.590000               74565.990000   \n",
       "75%       55.000000   3082.925000              120068.852500   \n",
       "max       65.000000  30427.680000              576335.680000   \n",
       "\n",
       "       Current Loan Expenses (USD)    Dependents  Credit Score  \\\n",
       "count                 19917.000000  18858.000000  19257.000000   \n",
       "mean                    408.462359      2.251246    738.821538   \n",
       "std                     215.846532      0.953153     72.406504   \n",
       "min                      41.370000      1.000000    580.040000   \n",
       "25%                     250.890000      2.000000    680.300000   \n",
       "50%                     374.000000      2.000000    739.300000   \n",
       "75%                     519.570000      3.000000    797.440000   \n",
       "max                    3305.970000     13.000000    893.830000   \n",
       "\n",
       "       No. of Defaults   Property ID  Property Age  Property Type  \n",
       "count     20000.000000  20000.000000  19108.000000    20000.00000  \n",
       "mean          0.189500    501.024500   2534.102003        2.47190  \n",
       "std           0.391915    287.537722   1408.509255        1.12551  \n",
       "min           0.000000      1.000000    368.590000        1.00000  \n",
       "25%           0.000000    252.000000   1658.397500        1.00000  \n",
       "50%           0.000000    501.000000   2220.605000        2.00000  \n",
       "75%           0.000000    748.000000   3082.250000        3.00000  \n",
       "max           1.000000    999.000000  30427.680000        4.00000  "
      ]
     },
     "execution_count": 22,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Generate summary statistics for numerical columns\n",
    "df.describe()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 23,
   "id": "8c001cc3",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Missing values per column:\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "Customer ID                       0\n",
       "Name                              0\n",
       "Gender                           31\n",
       "Age                               0\n",
       "Income (USD)                    750\n",
       "Income Stability                813\n",
       "Profession                        0\n",
       "Type of Employment             4689\n",
       "Location                          0\n",
       "Loan Amount Request (USD)         0\n",
       "Current Loan Expenses (USD)      83\n",
       "Expense Type 1                    0\n",
       "Expense Type 2                    0\n",
       "Dependents                     1142\n",
       "Credit Score                    743\n",
       "No. of Defaults                   0\n",
       "Has Active Credit Card         1076\n",
       "Property ID                       0\n",
       "Property Age                    892\n",
       "Property Type                     0\n",
       "Property Location               160\n",
       "Co-Applicant                      0\n",
       "Property Price                    0\n",
       "dtype: int64"
      ]
     },
     "execution_count": 23,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "# Check for missing values\n",
    "print(\"Missing values per column:\")\n",
    "df.isnull().sum()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 24,
   "id": "3d9f794c",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Index(['Customer ID', 'Name', 'Gender', 'Age', 'Income (USD)',\n",
       "       'Income Stability', 'Profession', 'Type of Employment', 'Location',\n",
       "       'Loan Amount Request (USD)', 'Current Loan Expenses (USD)',\n",
       "       'Expense Type 1', 'Expense Type 2', 'Dependents', 'Credit Score',\n",
       "       'No. of Defaults', 'Has Active Credit Card', 'Property ID',\n",
       "       'Property Age', 'Property Type', 'Property Location', 'Co-Applicant',\n",
       "       'Property Price'],\n",
       "      dtype='object')"
      ]
     },
     "execution_count": 24,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Lists the column names in the DataFrame.\n",
    "df.columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 25,
   "id": "a30bd0ec",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "Customer ID                     object\n",
       "Name                            object\n",
       "Gender                          object\n",
       "Age                              int64\n",
       "Income (USD)                   float64\n",
       "Income Stability                object\n",
       "Profession                      object\n",
       "Type of Employment              object\n",
       "Location                        object\n",
       "Loan Amount Request (USD)      float64\n",
       "Current Loan Expenses (USD)    float64\n",
       "Expense Type 1                  object\n",
       "Expense Type 2                  object\n",
       "Dependents                     float64\n",
       "Credit Score                   float64\n",
       "No. of Defaults                  int64\n",
       "Has Active Credit Card          object\n",
       "Property ID                      int64\n",
       "Property Age                   float64\n",
       "Property Type                    int64\n",
       "Property Location               object\n",
       "Co-Applicant                    object\n",
       "Property Price                  object\n",
       "dtype: object"
      ]
     },
     "execution_count": 25,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "#Shows the data types for each column\n",
    "df.dtypes"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "ca512794",
   "metadata": {},
   "source": [
    "---"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "43c2659c",
   "metadata": {},
   "source": [
    "# Data Exploration "
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e9c39092",
   "metadata": {},
   "source": [
    "Data exploration is the process of analyzing the DataFrame to understand distributions, patterns, and relationships within the data. It helps to generate hypotheses and guide further analysis or data manipulation."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "204710ae",
   "metadata": {},
   "source": [
    "Data Exploration Functions and their Meaning\n",
    "- **df[\"column\"].value_counts()**: Returns the count of unique values in a categorical column, helping understand the distribution.\n",
    "- **df[\"column\"].unique()**: Lists all unique values in a column, useful for understanding diversity in the data.\n",
    "- **df.corr()**: Computes the correlation matrix for numerical columns, indicating relationships between variables."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "e7c381b7",
   "metadata": {},
   "source": [
    "There are other techniques too which involves plots like histograms, heatmaps and scatterplot which we will learn and discuss in seaborn and matplotlib."
   ]
  },
  {
   "cell_type": "markdown",
   "id": "542ef1fa",
   "metadata": {},
   "source": [
    "### .value_counts()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 26,
   "id": "54766b19",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Gender Counts:\n",
      "F    10142\n",
      "M     9827\n",
      "Name: Gender, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# Get counts of unique values in the 'Gender' column\n",
    "gender_counts = df[\"Gender\"].value_counts()\n",
    "print(\"Gender Counts:\")\n",
    "print(gender_counts)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "8ec90e36",
   "metadata": {},
   "source": [
    "Shows there are 10142 Females whereas 9827 males in the 'gender' columns"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 27,
   "id": "1726435d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Location Counts:\n",
      "Semi-Urban    14463\n",
      "Rural          3436\n",
      "Urban          2101\n",
      "Name: Location, dtype: int64\n"
     ]
    }
   ],
   "source": [
    "# Get the count of unique values in the \"Location\" column\n",
    "location_counts = df[\"Location\"].value_counts()\n",
    "print(\"Location Counts:\")\n",
    "print(location_counts)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "7a14ef9b",
   "metadata": {},
   "source": [
    "Shows the number of location counts"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "31eb648c",
   "metadata": {},
   "source": [
    "### .unique()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 28,
   "id": "12b6130c",
   "metadata": {
    "scrolled": true
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unique Genders:\n",
      "['F' 'M' nan]\n"
     ]
    }
   ],
   "source": [
    "# Get the unique values in the \"Gender\" column\n",
    "unique_genders = df[\"Gender\"].unique()\n",
    "print(\"Unique Genders:\")\n",
    "print(unique_genders)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "995b2ae0",
   "metadata": {},
   "source": [
    "Shows the number of unique values in the gender column"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 29,
   "id": "ef5528fc",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Unique Locations:\n",
      "['Semi-Urban' 'Rural' 'Urban']\n"
     ]
    }
   ],
   "source": [
    "# Get the unique values in the \"Location\" column\n",
    "unique_locations = df[\"Location\"].unique()\n",
    "print(\"Unique Locations:\")\n",
    "print(unique_locations)"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "cecf4770",
   "metadata": {},
   "source": [
    "Shows the number of unique values in the 'location' column"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "5c713cc5",
   "metadata": {},
   "source": [
    "### corr()"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "db35525a",
   "metadata": {},
   "source": [
    "Correlation refers to a statistical measure that describes the degree to which two or more variables move in relation to each other.\n",
    "- A correlation coefficien, can range from -1 to +1"
   ]
  },
  {
   "cell_type": "markdown",
   "id": "aaed246f",
   "metadata": {},
   "source": [
    "Here, it is shown in the form of *Correlation Matrix*"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 30,
   "id": "1a88a396",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Correlation Matrix:\n",
      "                                Age  Income (USD)  Loan Amount Request (USD)\n",
      "Age                        1.000000      0.048481                   0.068921\n",
      "Income (USD)               0.048481      1.000000                   0.047194\n",
      "Loan Amount Request (USD)  0.068921      0.047194                   1.000000\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "C:\\Users\\manis\\AppData\\Local\\Temp\\ipykernel_16888\\3590295665.py:1: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.\n",
      "  correlation_matrix = data2.corr()\n"
     ]
    }
   ],
   "source": [
    "correlation_matrix = data2.corr()\n",
    "\n",
    "print(\"Correlation Matrix:\")\n",
    "print(correlation_matrix)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "5d75ef4f",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
